// <auto-generated />
using System;
using ActorsCastings.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActorsCastings.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241209085236_CorrectedUserNamePropertyInUserSeed")]
    partial class CorrectedUserNamePropertyInUserSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorsCastings.Data.Models.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Actor profile unique identifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasComment("Age of the actor");

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Portfolio of the actor");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("First name of the actor");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Last name of the actor");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Url of the profile picture of the actor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to User");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f6d3a0c-b710-4e8d-ae81-460396b39a91"),
                            Age = 44,
                            Biography = "Zahari Baharov was born on August 12, 1980 in Sofia. He started acting by accident in high school, and in 1998 was admitted to NATFIZ in the class of prof. Nadezhda Seikova and graduated in 2002.",
                            FirstName = "Zahari",
                            IsDeleted = false,
                            LastName = "Baharov",
                            ProfilePictureUrl = "https://nationaltheatre.bg/storage/profiles/28079f3b7c33cc2e5a34a62aa023631f86d.jpg",
                            UserId = new Guid("00437133-5332-45a7-952e-dc8b6b740b76")
                        },
                        new
                        {
                            Id = new Guid("01bd7e28-6449-4efc-9f1f-f70a29caaac3"),
                            Age = 47,
                            Biography = "Born on December 14, 1977. in Sofia. As a child, in the 1980s, he participated in television films for the Bulgarian Television. He received his secondary education at NGDEK. In the year 2000 graduated from NATFIZ with a major in acting for dramatic theater in the class of professor Snezhina Tankovska and associate professor Andrey Batashov.",
                            FirstName = "Teodora",
                            IsDeleted = false,
                            LastName = "Duhovnikova",
                            ProfilePictureUrl = "https://nationaltheatre.bg/storage/profiles/61272290fa286b2621edbb2f92ee5cfd8c.JPG",
                            UserId = new Guid("efc80aaa-7890-4f3f-80c0-5a86b0afe157")
                        },
                        new
                        {
                            Id = new Guid("44c54c7a-b031-404c-afd6-830dd00e7b83"),
                            Age = 31,
                            Biography = "He graduated from NATFIZ Krastyo Sarafov in 2017. in the class of prof. Ivaylo Hristov.",
                            FirstName = "Nencho",
                            IsDeleted = false,
                            LastName = "Kostov",
                            ProfilePictureUrl = "https://alternativavestnik.home.blog/wp-content/uploads/2023/02/received_1184727408853038.jpeg?w=683",
                            UserId = new Guid("0719936f-703e-4836-ade1-1d00e7225256")
                        },
                        new
                        {
                            Id = new Guid("8141b06f-e8e8-4988-b317-c43665f74e8a"),
                            Age = 54,
                            Biography = "Graduated acting at Luben Groys Theater College in the class of Professor Tsvetana Maneva in 2001. He made his debut on the stage of the Ivan Vazov National Theater in Romeo and Juliet by William Shakespeare, staged by Lilia Abadzhieva.",
                            FirstName = "Julian",
                            IsDeleted = false,
                            LastName = "Vergov",
                            ProfilePictureUrl = "https://interview.to/wp-content/uploads/2015/09/img_1755.jpg",
                            UserId = new Guid("be1c5570-a3dd-444a-9d43-bc0fef22a105")
                        },
                        new
                        {
                            Id = new Guid("072212c8-bfb2-4179-802c-3cc46648bbdc"),
                            Age = 66,
                            Biography = "He was born in Sofia, Bulgaria. His father is Nikola Penev, a journalist from the Zemedelsko zname newspaper. He completed his secondary education at Vasil Levski 8th Secondary School. Since 1982 is a master of acting for dramatic theater in the class of prof. Nikolay Lyutskanov with assistant Margarita Mladenova, VITIZ Krastyo Sarafov.",
                            FirstName = "Vladimir",
                            IsDeleted = false,
                            LastName = "Penev",
                            ProfilePictureUrl = "https://nationaltheatre.bg/storage/profiles/517ce32090fd407133468811fd50563a9.jpg",
                            UserId = new Guid("c36656b1-d6c7-4682-92fd-2b5f5c982241")
                        });
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.ActorCasting", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Actor");

                    b.Property<Guid>("CastingId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Casting");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.HasKey("ActorId", "CastingId");

                    b.HasIndex("CastingId");

                    b.ToTable("ActorsCastings");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.ActorMovie", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Actor");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Movie");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is the part of the actor in the movie approved by Admin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The role of the actor in the movie");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("ActorsMovies");

                    b.HasData(
                        new
                        {
                            ActorId = new Guid("0f6d3a0c-b710-4e8d-ae81-460396b39a91"),
                            MovieId = new Guid("7f3c4a10-2f6f-4434-840b-73f135c83aca"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Andrey Bogatev"
                        },
                        new
                        {
                            ActorId = new Guid("01bd7e28-6449-4efc-9f1f-f70a29caaac3"),
                            MovieId = new Guid("d5aa5fca-551e-4721-a332-b56a5821dd73"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Bilyana"
                        },
                        new
                        {
                            ActorId = new Guid("0f6d3a0c-b710-4e8d-ae81-460396b39a91"),
                            MovieId = new Guid("0276d235-774d-441f-ac77-9badafc4d814"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Sursuvul"
                        },
                        new
                        {
                            ActorId = new Guid("01bd7e28-6449-4efc-9f1f-f70a29caaac3"),
                            MovieId = new Guid("0276d235-774d-441f-ac77-9badafc4d814"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Mariam"
                        },
                        new
                        {
                            ActorId = new Guid("0f6d3a0c-b710-4e8d-ae81-460396b39a91"),
                            MovieId = new Guid("688dec9c-6a78-4769-80cc-b2281c4c7d2a"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Ivo Andonov"
                        },
                        new
                        {
                            ActorId = new Guid("072212c8-bfb2-4179-802c-3cc46648bbdc"),
                            MovieId = new Guid("688dec9c-6a78-4769-80cc-b2281c4c7d2a"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Emil Popov"
                        },
                        new
                        {
                            ActorId = new Guid("44c54c7a-b031-404c-afd6-830dd00e7b83"),
                            MovieId = new Guid("0276d235-774d-441f-ac77-9badafc4d814"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Petar"
                        },
                        new
                        {
                            ActorId = new Guid("8141b06f-e8e8-4988-b317-c43665f74e8a"),
                            MovieId = new Guid("cbe7da20-087d-4f57-bd21-9b9af1690bc1"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Nikola"
                        },
                        new
                        {
                            ActorId = new Guid("072212c8-bfb2-4179-802c-3cc46648bbdc"),
                            MovieId = new Guid("7f3c4a10-2f6f-4434-840b-73f135c83aca"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "The chief"
                        },
                        new
                        {
                            ActorId = new Guid("01bd7e28-6449-4efc-9f1f-f70a29caaac3"),
                            MovieId = new Guid("688dec9c-6a78-4769-80cc-b2281c4c7d2a"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Elica Vladeva"
                        });
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.ActorPlay", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Actor");

                    b.Property<Guid>("PlayId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to Play");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is the part of the actor in the play approved by Admin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The role of the actor in the play");

                    b.HasKey("ActorId", "PlayId");

                    b.HasIndex("PlayId");

                    b.ToTable("ActorsPlays");

                    b.HasData(
                        new
                        {
                            ActorId = new Guid("072212c8-bfb2-4179-802c-3cc46648bbdc"),
                            PlayId = new Guid("099134cb-ae73-4199-927c-9f84e1064710"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Andre"
                        },
                        new
                        {
                            ActorId = new Guid("8141b06f-e8e8-4988-b317-c43665f74e8a"),
                            PlayId = new Guid("099134cb-ae73-4199-927c-9f84e1064710"),
                            IsApproved = true,
                            IsDeleted = false
                        },
                        new
                        {
                            ActorId = new Guid("01bd7e28-6449-4efc-9f1f-f70a29caaac3"),
                            PlayId = new Guid("099134cb-ae73-4199-927c-9f84e1064710"),
                            IsApproved = true,
                            IsDeleted = false
                        },
                        new
                        {
                            ActorId = new Guid("01bd7e28-6449-4efc-9f1f-f70a29caaac3"),
                            PlayId = new Guid("9abd46e4-9f75-41a9-8cc3-d142997c04cf"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "She"
                        },
                        new
                        {
                            ActorId = new Guid("0f6d3a0c-b710-4e8d-ae81-460396b39a91"),
                            PlayId = new Guid("9abd46e4-9f75-41a9-8cc3-d142997c04cf"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "He"
                        },
                        new
                        {
                            ActorId = new Guid("44c54c7a-b031-404c-afd6-830dd00e7b83"),
                            PlayId = new Guid("253a0612-1359-4c37-a6b2-75593ea3320e"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Sergei"
                        },
                        new
                        {
                            ActorId = new Guid("44c54c7a-b031-404c-afd6-830dd00e7b83"),
                            PlayId = new Guid("cef3172a-d9ae-41c7-834f-cd934a506b95"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Stubb"
                        },
                        new
                        {
                            ActorId = new Guid("072212c8-bfb2-4179-802c-3cc46648bbdc"),
                            PlayId = new Guid("cef3172a-d9ae-41c7-834f-cd934a506b95"),
                            IsApproved = true,
                            IsDeleted = false,
                            Role = "Ishmael"
                        });
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00437133-5332-45a7-952e-dc8b6b740b76"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8bc6cd98-e87e-474b-8a87-3db809487bd7",
                            Email = "ivanivanov1@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV1@ABV.BG",
                            NormalizedUserName = "IVANIVANOV1@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEAOtSYzyefjnucipwjU6wGBNuqLQ7T7jPXllslVQ8WciOwQvIMt7dvnKf7TuO4U5DA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "217138eb-144c-49bc-b76d-42c61ec89fec",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov1@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("efc80aaa-7890-4f3f-80c0-5a86b0afe157"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e2bbfbc-5f61-4beb-894a-895604f7cacb",
                            Email = "ivanivanov2@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV2@ABV.BG",
                            NormalizedUserName = "IVANIVANOV2@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEDTDV3otRZFlRHS/mnflLeb3c14s+HScsyV0OVtiIlCWPAXeF0On4/j24SvBAn4A4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d0860d2b-1212-420b-baf1-e448c996cf90",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov2@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("0719936f-703e-4836-ade1-1d00e7225256"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "815ad42e-9bfb-474e-ac54-0a41c672cd4f",
                            Email = "ivanivanov3@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV3@ABV.BG",
                            NormalizedUserName = "IVANIVANOV3@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEMXPQeB1DN9pT3dJtXR/uMToNQTMYQEq0DbQyMNVRFZvI8JHJLWkyG/dPeG+orghtw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9a6f1233-3142-4720-878e-7192a4ae1cbc",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov3@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("be1c5570-a3dd-444a-9d43-bc0fef22a105"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3300f8bd-6e70-4a95-96c7-451619330551",
                            Email = "ivanivanov4@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV4@ABV.BG",
                            NormalizedUserName = "IVANIVANOV4@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEO7TKl6GSGnG3tGL60pT7XimFJt5vO6V5Lmq0Xdi9IOhA3oyu0Tjp9hGiVe7wKjTaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf3fef4f-b428-42ee-9e53-e6cc3f66409b",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov4@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("c36656b1-d6c7-4682-92fd-2b5f5c982241"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0cbc225b-adcf-4ec2-8596-1f74ec724c62",
                            Email = "ivanivanov5@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV5@ABV.BG",
                            NormalizedUserName = "IVANIVANOV5@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEKzj1HifRZmFgLGHN1363ZLjHPjI+XqKQCH2lA/ibeE9IrE9XhJgFixXhE9ZRMh+7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "645ca1c0-e9a2-4acc-98bf-a2235ea3a27b",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov5@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("386f0ce1-1884-4c63-beb0-746bb8e73634"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "786faf26-823f-48ee-8255-2b6efc417c67",
                            Email = "ivanivanov6@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV6@ABV.BG",
                            NormalizedUserName = "IVANIVANOV6@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAENALEvbPwRfPyah0NJnVHzje+HjnpKc7IaAhZPaeoE6Z93Uq0Yzx+5WradW/+xtllw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37ae8571-b3d6-4e35-bb2c-c66f5df37592",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov6@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("e5aeebb4-3d1b-4c8b-b19e-1ea073938b16"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8daa9673-b988-4a26-9299-3a209e085ce6",
                            Email = "ivanivanov7@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV7@ABV.BG",
                            NormalizedUserName = "IVANIVANOV7@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEMLhKp4yTsKDysEafY4kajZ0BTmIF3eEffR8/ngmqJyGob5ucfx/bJNVq7EzeUTJBg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1391658-0b75-4b97-b7f9-e8cda1d658fe",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov7@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("0487d986-ece3-4f68-9e3a-2d064f15a14a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1eb726b5-6675-4e17-9942-282618442d44",
                            Email = "ivanivanov8@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV8@ABV.BG",
                            NormalizedUserName = "IVANIVANOV8@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEBPEt9pRGTnzWnI47b+MAK0e1165vFMUch5YlietWYLQuIisIsY0kseNNkSTK0I2ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f7fd6461-0a77-47ca-96a3-f10a05100b0a",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov8@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("e9e3fa9c-ff55-4788-9085-cd00806062ec"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "801421e6-3396-4f55-b2e6-247c75198b97",
                            Email = "ivanivanov9@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV9@ABV.BG",
                            NormalizedUserName = "IVANIVANOV9@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEM0rcUZfu+OVRfSemy3AJB5NwkylNjAhKYv6NPyHN8lL4wL+snTRsfQMQquKD3M8lQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77fc4f2f-5d60-4ac7-927a-f45f03849e21",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov9@abv.bg"
                        },
                        new
                        {
                            Id = new Guid("a5faafe7-4729-4102-a2de-adf525f9d042"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1acb747b-de13-421f-b381-c07603e60a81",
                            Email = "ivanivanov10@abv.bg",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "IVANIVANOV10@ABV.BG",
                            NormalizedUserName = "IVANIVANOV10@ABV.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEC4rgEtSOxiEiQJRG8H2NJEQtR91U0RV3iGYOq7sy5jZ96V/g7mtCpoHyAbGrczWng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31d04655-d49f-45b2-adf5-88131c6589c4",
                            TwoFactorEnabled = false,
                            UserName = "ivanivanov10@abv.bg"
                        });
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Casting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Casting unique identifier");

                    b.Property<Guid>("CastingAgentId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The Casting agent that has created the casting - foreign key");

                    b.Property<DateTime>("CastingEnd")
                        .HasColumnType("datetime2")
                        .HasComment("The day and time the casting ends");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date the casting has been created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Description of the casting");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is the Casting approved by Admin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Casting title");

                    b.HasKey("Id");

                    b.HasIndex("CastingAgentId");

                    b.ToTable("Castings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f857443-4eec-42b0-9ed0-101973987ad7"),
                            CastingAgentId = new Guid("f5208d8b-a974-43ed-b8b0-54826c061a6e"),
                            CastingEnd = new DateTime(2024, 12, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 11, 25, 1, 42, 40, 0, DateTimeKind.Unspecified),
                            Description = "We're looking for a woman at an age from 25 to 35 for a secondary role in new movie",
                            IsApproved = true,
                            IsDeleted = false,
                            Title = "Movie Casting Woman"
                        },
                        new
                        {
                            Id = new Guid("5656965a-e13f-43d3-9754-639f3398191c"),
                            CastingAgentId = new Guid("8d91e4cf-b8d7-4cbd-938f-e377fb6913e2"),
                            CastingEnd = new DateTime(2024, 12, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 11, 24, 1, 42, 40, 0, DateTimeKind.Unspecified),
                            Description = "We're looking for a man at an age from 55 to 65 for a main role in new TV series. The actor should have a beard and white hair.",
                            IsApproved = true,
                            IsDeleted = false,
                            Title = "TV Series Casting for a man"
                        },
                        new
                        {
                            Id = new Guid("cfac6138-1a01-4a9b-a3c6-e52d32640124"),
                            CastingAgentId = new Guid("f5208d8b-a974-43ed-b8b0-54826c061a6e"),
                            CastingEnd = new DateTime(2024, 12, 23, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 11, 23, 1, 42, 40, 0, DateTimeKind.Unspecified),
                            Description = "We're looking for a woman at an age from 18 to 26 for a role in a sports ad. The actress should know how to swim.",
                            IsApproved = true,
                            IsDeleted = false,
                            Title = "Sports ad Casting for a young woman"
                        },
                        new
                        {
                            Id = new Guid("7ff7f307-2277-48f8-9533-b47345f43c00"),
                            CastingAgentId = new Guid("8b299bb7-7857-49be-b953-47d0961d6de7"),
                            CastingEnd = new DateTime(2024, 12, 24, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 11, 22, 1, 42, 40, 0, DateTimeKind.Unspecified),
                            Description = "We're looking for a man at an age from 25 to 35 for a main role in new action movie. The actor should have athletic skills.",
                            IsApproved = true,
                            IsDeleted = false,
                            Title = "Casting a man for new action movie"
                        },
                        new
                        {
                            Id = new Guid("1c801301-f82a-4c69-aedf-8aef41afb68b"),
                            CastingAgentId = new Guid("dc9a62c2-46f0-41b6-8fc2-0975dfba24bb"),
                            CastingEnd = new DateTime(2024, 12, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 11, 21, 1, 42, 40, 0, DateTimeKind.Unspecified),
                            Description = "We're looking for a woman at an age from 30 to 40 and a boy aged 6 to 9 for a Coca Cola ad.",
                            IsApproved = true,
                            IsDeleted = false,
                            Title = "Coca Cola Casting for a mother and a little boy"
                        });
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.CastingAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Casting agent profile unique identifier");

                    b.Property<string>("CastingAgency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the casting agency the agent works for");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Name of the casting agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign key to User");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CastingAgents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5208d8b-a974-43ed-b8b0-54826c061a6e"),
                            CastingAgency = "SmartCast",
                            IsDeleted = false,
                            Name = "Petar Ivanov",
                            UserId = new Guid("386f0ce1-1884-4c63-beb0-746bb8e73634")
                        },
                        new
                        {
                            Id = new Guid("8d91e4cf-b8d7-4cbd-938f-e377fb6913e2"),
                            CastingAgency = "Artist Studio",
                            IsDeleted = false,
                            Name = "Maria Ivanova",
                            UserId = new Guid("e5aeebb4-3d1b-4c8b-b19e-1ea073938b16")
                        },
                        new
                        {
                            Id = new Guid("8b299bb7-7857-49be-b953-47d0961d6de7"),
                            CastingAgency = "New Actors Studio",
                            IsDeleted = false,
                            Name = "Martin Georgiev",
                            UserId = new Guid("0487d986-ece3-4f68-9e3a-2d064f15a14a")
                        },
                        new
                        {
                            Id = new Guid("dc9a62c2-46f0-41b6-8fc2-0975dfba24bb"),
                            CastingAgency = "Cast.bg",
                            IsDeleted = false,
                            Name = "Anna Petkova",
                            UserId = new Guid("e9e3fa9c-ff55-4788-9085-cd00806062ec")
                        },
                        new
                        {
                            Id = new Guid("b3ddcdfc-21fb-4b60-8e99-8386cea3155a"),
                            CastingAgency = "CastingCrew",
                            IsDeleted = false,
                            Name = "Dimitar Dimitrov",
                            UserId = new Guid("a5faafe7-4729-4102-a2de-adf525f9d042")
                        });
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Movie unique identifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Description of the movie");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Movie director name");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Genre of the movie");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the movie");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is the Movie approved by Admin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int")
                        .HasComment("Release year of the movie");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Movie title");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f3c4a10-2f6f-4434-840b-73f135c83aca"),
                            Description = "Follows the parallel stories of a number of characters who are trying to change their lives via the Internet or are simply having fun online.",
                            Director = "Ilian Djevelekov",
                            Genre = "Drama",
                            ImageUrl = "https://www.cinefish.bg/data/movies_images/138/p_138649.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2011,
                            Title = "Love.net"
                        },
                        new
                        {
                            Id = new Guid("d5aa5fca-551e-4721-a332-b56a5821dd73"),
                            Description = "Kalin (35) is a talented advertising specialist, weary of life. Bilyana (35) is a free spirit, still uncertain of what she wants. They grew up in Socialist Bulgaria, where they were part of a mad group of friends, for whom every day was a different adventure. Childlike, they had a pact to get married. The two of them meet 25 years later.",
                            Director = "Stanislav Todorov Rogi",
                            Genre = "Drama",
                            ImageUrl = "https://www.ciela.com/media/catalog/product/cache/9a7ceae8a5abbd0253425b80f9ef99a5/d/y/dyvka-za-baloncheta-dvd.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2017,
                            Title = "Bubblegum"
                        },
                        new
                        {
                            Id = new Guid("0276d235-774d-441f-ac77-9badafc4d814"),
                            Description = "10th century, the most powerful state in Europe rests on a terrible secret that may threaten the very foundations of Christianity. Captured between political intrigues and warrior battles the young prince Bayan is searching for an ancient alphabet that could save his doomed love or his kingdom. A medieval mystery drama about the birth of the Cyrillic alphabet.",
                            Director = "Zoran Petrovski, Viktor Chuchkov",
                            Genre = "History Drama",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZDljYzNlNmMtNTViYi00N2Y1LWFiOTItYzhkMzBiMzY0ZDM3XkEyXkFqcGc@._V1_.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2022,
                            Title = "War of Letters"
                        },
                        new
                        {
                            Id = new Guid("688dec9c-6a78-4769-80cc-b2281c4c7d2a"),
                            Description = "Trained young policeman goes undercover in the gang of the most dangerous mafia boss in Bulgaria.",
                            Director = "Victor Bojinov",
                            Genre = "Action",
                            ImageUrl = "https://www.vivacom.bg/web/files/arena/630/image/thumb_388x564_%D0%9F%D0%BE%D0%B4%20%D0%BF%D1%80%D0%B8%D0%BA%D1%80%D0%B8%D1%82%D0%B8%D0%B5.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2011,
                            Title = "Undercover"
                        },
                        new
                        {
                            Id = new Guid("cbe7da20-087d-4f57-bd21-9b9af1690bc1"),
                            Description = "A middle aged man named Nikola is struggling with his life in his home country Bulgaria. He decides to move to Germany and is desperately trying to restore relationships with all his beloved people, just a day before he leaves. This is director's first feature film.",
                            Director = "Pavel G. Vesnakov",
                            Genre = "Drama",
                            ImageUrl = "https://www.bta.bg/upload/4349066/Vergov_Fyre.jpg?l=1000&original=41849178c4da42705e2edc8c815ef18546c6d52e",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2020,
                            Title = "German Lessons"
                        });
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Play unique identifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Description of the play");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Play director name");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the play");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is the Play approved by Admin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Soft delete");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int")
                        .HasComment("Release year of the play");

                    b.Property<string>("Theatre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The theatre where the play is played");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Play title");

                    b.HasKey("Id");

                    b.ToTable("Plays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("099134cb-ae73-4199-927c-9f84e1064710"),
                            Description = "The Father by the French playwright Florian Zeller is an absolute hit on the theater stages of New York, Paris, Berlin and London. The virtuoso plot immerses the main character Andre in a world of branching identities.",
                            Director = "Diana Dobreva",
                            ImageUrl = "https://nationaltheatre.bg/storage/shows/6635392173eb94e9023a68ea3568f7e031.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2018,
                            Theatre = "National Theatre Ivan Vazov",
                            Title = "The Father"
                        },
                        new
                        {
                            Id = new Guid("9abd46e4-9f75-41a9-8cc3-d142997c04cf"),
                            Description = "What can we say? When? In what way? Under what circumstances? Although we take free speech for granted, there are things that can no longer be said. Especially in the relationship between man and woman. However, they tell each other everything. Two characters with hellish personalities. He is unscrupulous, provocative and does not keep silent. She is unfiltered, sassy and arrogant. They love each other, but spend most of their time arguing and arguing.",
                            Director = "Yavor Gardev",
                            ImageUrl = "https://artvent.bg/images/news/163fc676768c8c.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2023,
                            Theatre = "Artvent Theatre",
                            Title = "Don't say that!"
                        },
                        new
                        {
                            Id = new Guid("253a0612-1359-4c37-a6b2-75593ea3320e"),
                            Description = "Alexey Salnikov's novel Petrovi in ​​and around the flu caused a sensation in Russia in 2016, and a year later won the NOS and National Bestseller critics' awards. The probability that the stage version and the spectacle of the director Boyan Kracholov will cause a sensation is equally great.",
                            Director = "Boyan Kracholov",
                            ImageUrl = "https://nationaltheatre.bg/storage/shows/21896537f742a18038a69548af7cd69b356.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2023,
                            Theatre = "National Theatre Ivan Vazov",
                            Title = "Petrov's Flu"
                        },
                        new
                        {
                            Id = new Guid("cef3172a-d9ae-41c7-834f-cd934a506b95"),
                            Description = "The play Moby Dick, based on Herman Melville's novel, tells the story of Captain Ahab, chasing a majestic white whale around the globe. In the biblical journey he is accompanied by a crew ready to go with him to the end. Far from them remain their wives, whose dreams determine the direction of the ship.",
                            Director = "Diana Dobreva",
                            ImageUrl = "https://nationaltheatre.bg/storage/shows/232d06b4cc9e283a6ca63f0ac051c7fbeed.png",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2024,
                            Theatre = "National Theatre Ivan Vazov",
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = new Guid("d49574dd-ab22-4b5c-9de6-892c09e786f3"),
                            Description = "Medea's name easily conjures up the image of a screaming monster-killer from Antiquity. But the truth is that Euripides brings Medea's experience uncomfortably close to each of us. His Medea is a very real woman who faces an overwhelming ordeal.",
                            Director = "Declan Donnellan",
                            ImageUrl = "https://nationaltheatre.bg/storage/shows/257bd0afd723a7d282d77ab2815962c295a.jpg",
                            IsApproved = true,
                            IsDeleted = false,
                            ReleaseYear = 2024,
                            Theatre = "National Theatre Ivan Vazov",
                            Title = "Medea"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Actor", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.ActorCasting", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.Actor", "Actor")
                        .WithMany("ActorsCastings")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActorsCastings.Data.Models.Casting", "Casting")
                        .WithMany("ActorsCastings")
                        .HasForeignKey("CastingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Casting");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.ActorMovie", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.Actor", "Actor")
                        .WithMany("ActorsMovies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActorsCastings.Data.Models.Movie", "Movie")
                        .WithMany("ActorsMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.ActorPlay", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.Actor", "Actor")
                        .WithMany("ActorsPlays")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActorsCastings.Data.Models.Play", "Play")
                        .WithMany("ActorsPlays")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Casting", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.CastingAgent", "CastingAgent")
                        .WithMany("Castings")
                        .HasForeignKey("CastingAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastingAgent");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.CastingAgent", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActorsCastings.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ActorsCastings.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Actor", b =>
                {
                    b.Navigation("ActorsCastings");

                    b.Navigation("ActorsMovies");

                    b.Navigation("ActorsPlays");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Casting", b =>
                {
                    b.Navigation("ActorsCastings");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.CastingAgent", b =>
                {
                    b.Navigation("Castings");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Movie", b =>
                {
                    b.Navigation("ActorsMovies");
                });

            modelBuilder.Entity("ActorsCastings.Data.Models.Play", b =>
                {
                    b.Navigation("ActorsPlays");
                });
#pragma warning restore 612, 618
        }
    }
}
